site_name: 基于低维模型的高维数据分析方法与应用
site_url: https://zhappyhammer.github.io/mayibook
nav:
    - Home: index.md
    - 第1章-简介: 
        - ch1/1.1.md
        - ch1/1.2.md
        - ch1/1.3.md
        - ch1/1.4.md
    - 第1部分-低维模型原理:
        - 第2章-稀疏信号模型: 
            - ch2/index.md
        - 第3章-基于凸方法的稀疏信号恢复: 
            - ch3/index.md
        - 第4章-基于凸方法的低秩矩阵恢复: 
            - ch4/index.md
        - 第5章-低秩矩阵和稀疏矩阵的分解: 
            - ch5/index.md
        - 第6章-恢复通用低维模型: 
            - ch6/index.md
        - 第7章-低维模型的非凸方法: 
            - ch7/index.md
    - 第2部分-大规模问题的计算:
        - 第8章-基于凸优化的结构化信号恢复: 
            - ch8/index.md
        - 第9章-高维问题的非凸优化: 
            - ch9/index.md
    - 第3部分-应用:
        - 第10章-磁共振成像: 
            - ch10/index.md
        - 第11章-宽带频谱感知: 
            - ch11/index.md
        - 第12章-科学成像问题: 
            - ch12/index.md
        - 第13章-人脸识别的鲁棒性: 
            - ch13/index.md
        - 第14章-光度立体视觉的三维重建鲁棒性: 
            - ch14/index.md
        - 第15章-结构化纹理复原: 
            - ch15/index.md
        - 第16章-用于分类的深度网络: 
            - ch16/index.md
    - 附录:
        - 附录A-线性代数与矩阵分析: 
            - appendix/a/index.md
            - appendix/a/1.md
            - appendix/a/2.md
            - appendix/a/3.md
            - appendix/a/4.md
            - appendix/a/5.md
            - appendix/a/6.md
            - appendix/a/7.md
            - appendix/a/8.md
            - appendix/a/9.md
        - 附录B-凸集与凸函数:
            - appendix/b/index.md
            - appendix/b/b.md
        - 附录C-优化问题与最优性条件:
            - appendix/c/index.md 
            - appendix/c/c.md
        - 附录D-优化方法:
            - appendix/d/index.md 
            - appendix/d/d.md
        - 附录E-高维统计:
            - appendix/e/index.md 
            - appendix/e/e.md
theme:
    name: material
    favicon: images/favicon.ico
    logo: images/logo.jpeg
    palette:
        primary: "black"
        accent: "deep orange"
    language: zh
    features:
        - content.code.copy
        - navigation.tabs # 顶部显示导航顶层nav（也就是第一个节点）
        - navigation.tabs.sticky # 滚动时隐藏顶部nav，配合navigation.tabs使用
        - navigation.tracking # 在url中使用标题定位锚点
        - navigation.expand # 不折叠左侧nav节点
        # - navigation.sections # nav节点缩进
        - navigation.path
        - navigation.top # 一键回顶部
        - navigation.instant # 启用即时加载
        - navigation.indexes
        - toc.follow
markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
        linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    # 这个是设置页面支持latex公式的，下面四行都是
    - pymdownx.arithmatex:
        generic: true
extra_javascript:
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js


